spring:
  datasource:
    url: jdbc:mysql://containers-us-west-121.railway.app:6895/railway
    username: root
    password: eSOjPlEHhjlyArqvWgat
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true